name: Deploy via Jekyll on GitHub pages

on:
  push:
    branches:
    - source
  schedule:
  - cron: '0 0 * * *'

# TODO: permissions defined

jobs:
  jekyll:
    runs-on: ubuntu-latest

    if: github.repository == 'metal3-io/metal3-io.github.io'
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: iranzo/gh-pages-jekyll-action@d27999d323a83e1989f4b62f5176f0b4736066d3 # 1.0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: ./
        GH_PAGES_BRANCH: master
