name: Deploy via Jekyll on GitHub  pages

on:
  push:
    branches:
      - source
  schedule:
    - cron:  '0 0 * * *'

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: iranzo/gh-pages-jekyll-action@d27999d323a83e1989f4b62f5176f0b4736066d3 # 1.0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: ./
        GH_PAGES_BRANCH: master
