name: pre-commit

on:
  pull_request:
  push:
    branches: [source]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
