name: pre-commit

on:
  pull_request:
  push:
    branches: [source]

permissions:
  contents: read

jobs:
  pre-commit:
    if: github.repository == 'metal3-io/metal3-io.github.io'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
    - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
